# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes

#Yaml pliki
sensor: !include sensors.yaml

# Licznik F&F LE-03MW
modbus:
  - name: hub1
    type: serial
    baudrate: 9600
    port: /dev/ttyUSB0
    bytesize: 8
    method: rtu
    parity: E
    stopbits: 1
    sensors:
      - name: L1 - napięcie fazowe
        unit_of_measurement: V
        device_class: voltage
        slave: 1
        address: 14
        #   input_type: float32
        data_type: float32
        scan_interval: 5
      - name: L2 - napięcie fazowe
        unit_of_measurement: V
        device_class: voltage
        slave: 1
        address: 16
        data_type: float32
        scan_interval: 5
      - name: L3 - napięcie fazowe
        unit_of_measurement: V
        device_class: voltage
        slave: 1
        address: 18
        data_type: float32
        scan_interval: 5
      - name: L1 – Prąd fazowy
        unit_of_measurement: A
        device_class: power
        slave: 1
        address: 22
        data_type: float32
        precision: 2
        scan_interval: 5
      - name: L2 – Prąd fazowy
        unit_of_measurement: A
        device_class: power
        slave: 1
        address: 24
        data_type: float32
        precision: 2
        scan_interval: 5
      - name: L3 – Prąd fazowy
        unit_of_measurement: A
        device_class: power
        slave: 1
        address: 26
        data_type: float32
        precision: 2
        scan_interval: 5
      - name: L3 – Prąd fazowy
        unit_of_measurement: A
        device_class: power
        slave: 1
        address: 26
        data_type: float32
        scan_interval: 5
      - name: Całkowita moc czynna
        unit_of_measurement: kW
        device_class: power
        slave: 1
        address: 28
        data_type: float32
        precision: 3
        scan_interval: 5
      - name: Faza L1 – moc czynna
        unit_of_measurement: kW
        device_class: power
        slave: 1
        address: 30
        data_type: float32
        precision: 3
        scan_interval: 5
      - name: Faza L2 – moc czynna
        unit_of_measurement: kW
        device_class: power
        slave: 1
        address: 32
        data_type: float32
        precision: 3
        scan_interval: 5
      - name: Faza L3 – moc czynna
        unit_of_measurement: kW
        device_class: power
        slave: 1
        address: 34
        data_type: float32
        precision: 3
        scan_interval: 5
      - name: Częstotliwość
        unit_of_measurement: Hz
        device_class: power
        slave: 1
        address: 20
        data_type: float32
        precision: 2
        scan_interval: 5
      - name: Całkowita energia czynna
        state_class: total_increasing
        unit_of_measurement: kWh
        device_class: energy
        slave: 1
        address: 256
        data_type: float32
        precision: 2
        scan_interval: 5
      - name: Faza L1 – całkowita energia czynna
        unit_of_measurement: kWh
        device_class: energy
        slave: 1
        address: 258
        data_type: float32
        scan_interval: 5
      - name: Faza L2 – całkowita energia czynna
        unit_of_measurement: kWh
        device_class: energy
        slave: 1
        address: 260
        data_type: float32
        scan_interval: 5
      - name: Faza L3 – całkowita energia czynna
        unit_of_measurement: kWh
        device_class: energy
        slave: 1
        address: 262
        data_type: float32
        scan_interval: 5
      - name: Taryfa T1 – całkowita energia czynna
        unit_of_measurement: kWh
        device_class: energy
        slave: 1
        address: 304
        data_type: float32
        precision: 2
        scan_interval: 5

  # Rekuperacja Komfovent R600h
  - name: Komfovent
    type: tcp
    host: 192.168.1.111
    port: 502
    switches:
      - name: "Komfovent Auto"
        slave: 1
        address: 3
        command_on: 1
        command_off: 0
        verify:
      - name: "Komfovent Power"
        slave: 1
        address: 0
        command_on: 1
        command_off: 0
        verify:
      - name: "Komfovent Eco"
        slave: 1
        address: 2
        command_on: 1
        command_off: 0
        verify:
    sensors:
      - name: "Komfovent Power"
        address: 0
        scan_interval: 10
      - name: "Komfovent Eco"
        address: 2
        scan_interval: 10
      - name: "Komfovent Mode"
        address: 4
        scan_interval: 10
      - name: "Komfovent Auto"
        address: 3
        scan_interval: 10
      - name: "Komfovent Shedule"
        address: 5
        scan_interval: 10
      - name: "Komfovent Supply temperature 'C"
        address: 901
        scan_interval: 10
        unit_of_measurement: °C
        scale: 0.1
        precision: 1
      - name: "Komfovent Extract temperature 'C"
        address: 902
        scan_interval: 10
        unit_of_measurement: °C
        scale: 0.1
        precision: 1
      - name: "Komfovent Supply Flow '%"
        address: 905
        scan_interval: 10
        count: 2
        unit_of_measurement: "%"
        precision: 1
      - name: "Komfovent Extract Flow '%"
        address: 907
        scan_interval: 10
        count: 2
        unit_of_measurement: "%"
        precision: 1
      - name: "Komfovent Supply Fan Intensivity '%"
        address: 909
        scan_interval: 10
        unit_of_measurement: "%"
        scale: 0.1
        precision: 1
      - name: "Komfovent Extract Fan Intensivity %"
        address: 910
        scan_interval: 10
        unit_of_measurement: "%"
        scale: 0.1
        precision: 1
      - name: "Komfovent Outdoor temperature'C"
        address: 903
        scan_interval: 10
        unit_of_measurement: °C
        scale: 0.1
        precision: 1
      - name: "Komfovent Filter Dirt, %"
        address: 918
        scan_interval: 10
      - name: "Komfovent Filter Dirt, %"
        address: 917
        scan_interval: 10
      - name: "Komfovent Filter Impurity, %"
        address: 916
        scan_interval: 10
        unit_of_measurement: "%"
      - name: "Komfovent Heating power, W"
        address: 912
        scan_interval: 10
        unit_of_measurement: W
      - name: "Komfovent Power consumption, W"
        address: 920
        scan_interval: 10
        unit_of_measurement: W
      - name: "Komfovent Power consumption Month, kWh"
        address: 928
        scan_interval: 10
        unit_of_measurement: kWh
        count: 2
        precision: 0
        scale: 0.001
      - name: "Komfovent Heating Recovery Month, kWh"
        address: 940
        scan_interval: 10
        unit_of_measurement: kWh
        count: 2
        precision: 0
        scale: 0.001
      - name: "Komfovent Heating Recovery Total, kWh"
        address: 942
        scan_interval: 10
        unit_of_measurement: kWh
        count: 2
        precision: 0
        scale: 0.001
      - name: "Komfovent Heat Recovery, W"
        address: 922
        scan_interval: 10
        unit_of_measurement: W
      - name: "Komfovent Heat exchanger efficiency, %"
        address: 923
        scan_interval: 10
        scale: 1
        precision: 0
        unit_of_measurement: "%"
      - name: "Komfovent Energy saving, %"
        address: 924
        scan_interval: 10
      - name: "Komfovent Specific power (SPI)"
        address: 925
        scan_interval: 10
        scale: 0.001
        precision: 2
shell_command:
  komfovent_kitchen_mode: >-
    curl 'http://192.168.1.111/' --data-raw '1=user&2=user' &&
    curl 'http://192.168.1.111/ajax.xml' --data-raw '282=20'
